# Generated by Django 5.0.4 on 2024-04-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('volume', models.FloatField()),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
